### ISSUE TITLE
[BUG] Table 'ocsweb.softwares' doesn't exist

### ISSUE THREAD

**Issue by CyberAbwehr** [OCSInventory-NG/OCSInventory-ocsreports#1060]
**OCS Inventory version**
Version : 2.8

**Describe the bug**
I got following error message if I want to import OCS data to I-doit

i-doit OCS Import

OCS-Handler initialized (2020-11-03 11:24:55)
Starting Import.
Import failed
Error-Message: Database error : Query error: 'SELECT * FROM hardware INNER JOIN softwares ON softwares.HARDWARE_ID = hardware.ID AND softwares.NAME != '' WHERE hardware.ID = 1 AND hardware.OSNAME != softwares.NAME AND softwares.NAME NOT IN (SELECT EXTRACTED FROM dico_ignored)':
Table 'ocsweb.softwares' doesn't exist

In the ocsweb database the table softwares is missing.

only following tables are available

software
software_categories
software_category_exp
software_name
software_publisher
softwares_name_cache
software_version

Was there a database schema change in the ocsweb database?

maybe from softwares to software ?

**Comment by gillesdubois** [comment]
Hi @CyberAbwehr 

Indeed we changed the software table structure.
It seem your software (i-doit) didn't managed this data structure change.

I recommend you to get in touch with i-doit team so they can perform the changes with their connector.
In the mean time, I think you might need to rollback to keep a working import.

Also, here is an issue I created to a plugin from a third party tool named GLPI. https://github.com/pluginsGLPI/ocsinventoryng/issues/243

It can give you some information on what changes you need to perform in order to get it to work.

Regards,
Gilles.

**Comment by marioalpha** [comment]
upgrade from 2.6 to 2.9 same error.
The software table exists and contains the data, but from the GUI I have a blank page.

Error 500 only for new PCs, on these I temporarily set / NoSoftware = 1

How can I solve the problem ?
Wanting to go back where I find unix-server ver 2.6?
