### ISSUE TITLE
[BUG] Page visu_all_soft is empty

### ISSUE THREAD

**Issue by ewanoomen** [OCSInventory-NG/OCSInventory-ocsreports#1156]
**OCS Inventory version**
Version : 2.8.1

**Describe the bug**
The table on the page visu_all_soft is empty while the individual computers do contain software. This is on a clean install on Ubuntu 20.04.2. PHP version 7.4.3.

**To Reproduce**
1. Go to 'Inventory > All software'

**Expected behavior**
A table of all the software including how many times installed.

**Screenshots**
![Schermafbeelding 2021-03-22 210805](https://user-images.githubusercontent.com/42176794/112052050-ef1a7600-8b52-11eb-85e6-b4b7450673d4.png)
![Schermafbeelding 2021-03-22 210854](https://user-images.githubusercontent.com/42176794/112052067-f2adfd00-8b52-11eb-8158-0d10c202247e.png)

**Log file (optional)**
No errors in the Apache log

**Comment by charleneauger** [comment]
Hi @ewanoomen ,

Have you downloaded a release OCS Server version or cloned the GitHub master ?

Regards,
Charlene Auger

**Comment by ewanoomen** [comment]
It's a clone of the master

**Comment by charleneauger** [comment]
Hi @ewanoomen ,

Since the PR #1146 , the all software  page datas are generated from a crontab. This feature has been added to improve software query execution time. 
A documentation will be available soon.
To populate all sofwtare page, launch cron_all_software in ocsinventory-ng/ocsreports/crontab folder.

Best regards,
Charlene Auger

**Comment by ewanoomen** [comment]
Yes, @charleneauger thank you for the clarification!
