### ISSUE TITLE
Wrong number count

### ISSUE THREAD

**Issue by agintzari** [OCSInventory-NG/OCSInventory-ocsreports#1250]
In my OCS inventory panel I have many custom labels, but the new inventoried computers always go to NA label (default label). It always appears 6 new computers, but when I click in the number to check them, it is always empty. (**Inventory --> Computers per tag**)

I get used to know that I have a new inventoried computer when that number is above 6.

I attach two images.
![OCS1](https://user-images.githubusercontent.com/90321898/132501380-4bce79f8-88ba-4967-bef3-41aea01d3854.PNG)
![Ocs2](https://user-images.githubusercontent.com/90321898/132501385-0a04bcb7-fdae-4eac-a968-2aae41f017f7.PNG)

**Comment by Lea9250** [comment]
Hi @agintzari,

The wrong count might be caused by 'ghost entries' when devices are removed from OCS. Could you try executing this sql statement : 
```
SELECT accountinfo.HARDWARE_ID FROM accountinfo LEFT JOIN hardware ON accountinfo.HARDWARE_ID = hardware.ID WHERE hardware.ID IS NULL GROUP BY accountinfo.HARDWARE_ID;
```
It will return the hardware ids still present in your accountinfo table but not linked to any device in your hardware table.

If you do get an output from this, you can run 
```
SELECT CONCAT('DELETE FROM ',TABLE_NAME," WHERE hardware_id IN (hID1, hID2, hID3);") FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'ocsweb' AND COLUMN_NAME='hardware_id';
```
 next. Replace **hID**s in the above query by the ids retrieved by the previous command and **ocsweb** with your OCS database name.
You should get a set of DELETE queries from this. You can then copy/paste these to remove entries linked to hardware ids that are no longer in present in OCS. If you wish to only clean the accountinfo table, just pick the corresponding statement from the output and execute it.

Let me know how this goes,
Léa

**Comment by agintzari** [comment]
It works correctly! Thank you so much
