### ISSUE TITLE
Multivalue Fields: No Option to Add Values

### ISSUE THREAD

**Issue by rburkholder2305** [OCSInventory-NG/OCSInventory-ocsreports#127]
SELECT, CHECKBOX, and RADIOBUTTON field types can be created but give no option to add values.

![screenshot - 9_6_2016 14_33_33](https://cloud.githubusercontent.com/assets/19395042/18286036/014de080-743f-11e6-97fe-897252b8d85f.png)

OS: Ubuntu 16.04.1
Apache: 2.4.18
PHP: 7.0.8
OCS Inventory Version: 2.2.1

**Comment by gillesdubois** [comment]
Hi,

Could you be a little more precise on your request ?
I can't see what you mean by "give no option to add values."

Thanks for your contribution.
Regards,
Gilles Dubois.

**Comment by rburkholder2305** [comment]
Absolutely, when you select the field types SELECT, CHECKBOX, and RADIOBUTTON and click OK there is no way to add choices for those field types. It just creates a blank field with no values to choose from.

**Comment by gillesdubois** [comment]
Hi,

Your bug has been fixed in the RC.
If you create a select / radiobutton data ( checkbox can't contain multiples data ) you need to go on a computer's administrative data and click on the edit button.

![admin data edit](https://cloud.githubusercontent.com/assets/9396603/21483391/a36ca09c-cb81-11e6-9e11-0b037e00d7e6.png)
