### ISSUE TITLE
Adding monitor tab in show / hide dropdown

### ISSUE THREAD

**Issue by sachinmu** [OCSInventory-NG/OCSInventory-ocsreports#1390]
Hi Team 
Is it possible to add monitor or any other missing information in show/hide dropdown ? currently I see very few options in the dropdown

**Comment by gillesdubois** [comment]
Hi,

I think you are asking for the monitor view in the all computers page.
Unfortunately we cannot change the show / hide view and add monitor.
The issue is that on instance with a lot of agent, adding a JOIN in the SQL request to show monitors infos might lead to performance issues. 

I recommend to use the search with various criteria that allow you to show monitor related information.

Regards,
Gilles.
