### ISSUE TITLE
[FEATURE] deployments not sorted by date

### ISSUE THREAD

**Issue by Minikea** [OCSInventory-NG/OCSInventory-ocsreports#1471]
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**
In the deployment tab in the computer view, we can no longer sort by deployment date and have the last packages deployed on the computer in the bottom or top of the list. Timestamp is not relevant because we could deploy an old package and Comments are not sorted correctly.

**To Reproduce**
1. Go to deployment tab in a computer screen
2. Click on Comment
3. Note the list is sorted by letter instead of date

**Expected behavior**
A date column to sort by deployment date

**Comment by Minikea** [comment]
The feature was already active prior version 2.11. the list was ordered by date of deployment. There is a regression since 2.11.

**Comment by charleneauger** [comment]
@Minikea, 

Ok, I think I get your point. In the older version, the list was ordered by the creation ID which is why you had them in the deployment assignation order. Is that what you meant ?

![2 10](https://user-images.githubusercontent.com/28924550/227565024-60d0724e-9981-4418-9d7b-6ef2a91b2abe.png)

Since 2.11, we switched to a dynamic table view (using datatable) which doesn’t sort the data in the same way. The data is sorted by package name which is not really practical. Sorting by date directly would be a bit complex since the date is not a dedicated field but is part of the comment field.

![2 11](https://user-images.githubusercontent.com/28924550/227565072-eae97e43-150a-4e59-b37b-5e1e5b02396c.png)

We’ll check and try to sort as in the older versions or make a real date sort possible. You’ll be notified as soon as we push a pull request related to this issue :)

Best regards,
Charlene

**Comment by charleneauger** [comment]
@Minikea, can you integrate the changes I made in the PR #1500 and tell me if it rights for you ?

Regards,
Charlene

**Comment by Minikea** [comment]
The solution works and covers the demand.

Thanks.
