### ISSUE TITLE
[BUG] Wrong "Search with various criteria" result

### ISSUE THREAD

**Issue by tiagobortolini** [OCSInventory-NG/OCSInventory-ocsreports#1512]
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**

Our ocs agents collect two registry keys(LastLoggedOnUser and LastLoggedOnSAMUser) on client machines.
In the page "Search with various criteria", when searching by the criteria "Registry key : Name" Like "LastLogged"(so the search will get both LastLoggedOnUser and LastLoggedOnSAMUser), the result displays only one row per machine(in this case, it displays only lines for LastLoggedOnUser registry key).
The expected behavior is the page displaying two lines per machine.

I can get the correct result by commenting the "group by" line in the file 'require/search/Search.php', but I don't know if this change can mess up another searches:

`//$this->columnsQueryConditions .= " GROUP BY hardware.id";`

**To Reproduce**
1. Go to "Inventory/Search with various criteria"
2. Select "Registry Key" on the left drop down menu
3. Select "Name" on the right drop down menu
4. Click Add
5. Select "Like" on the left drop down menu of the line added
6. Type "LastLogged" on the right text box
7. Click Send
8. The result shows only one row per machine

**Expected behavior**

The result page should display both LastLoggedOnUser and LastLoggedOnSAMUser registry keys. It should display two lines per inventoried machine.

**Screenshots**

Wrong result(only LastLoggedOnUser line):

![ScreenHunter 240](https://user-images.githubusercontent.com/28762958/234672035-a113291e-f400-4212-b35c-2c4c544600be.png)

Correct Result(LastLoggedOnSAMUser line is displayed):

![ScreenHunter 241](https://user-images.githubusercontent.com/28762958/234672067-a8769045-d21c-4489-ac93-d3c7cfd79b3a.png)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by charleneauger** [comment]
Hi @tiagobortolini ,

The multi-criteria returns the number of machines that match the search performed.

In this sense, your first result is correct.

Unfortunately, I cannot validate the modification you want to make because it completely distorts the total number of machines returned by the search.

If you want to display only the machines having the two registry keys, I advise you to do the following search :

![Screenshot_20230524_103225](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/28924550/192e3066-3453-468a-9748-dce426a63059)

Best regards,
Charlene Auger
