### ISSUE TITLE
[BUG] less / more does not work with software versions

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#1597]
**OCS Inventory version**
Version : 2.12.1

**Describe the bug**
less than does not work properly with decimal numbers in the software search

the whole "less than" or "greater than" does not work properly (here the comparison is mathematical, not by version)

When calculating, 17.9 would be greater than 17.15, for software versions 17.15 is higher than 17.9.

**To Reproduce**
If you have software in version 17.6, it will be found at "less than 17.9.1", but not at "less than 17.10.1"

**Expected behavior**
If I have software version 17.6, this must be found under "less than 17.9.1" and "less than 17.10.1".

**Screenshots**
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/8693550/3cf9662b-e123-455d-9aa6-11fdc2d7d192)

**Comment by charleneauger** [comment]
Hi @LMS235 ,

The software version is referenced as a `String` field.
Since version 2.12.0, we have added the `Major version`, `Minor version` and `Patch version` fields. These fields are referenced as `Integer` which allows a numerical search/comparison.

We advise you to use these fields if you want to search with `less than` or `more than`.

Best regards,
Charlene

**Comment by LMS235** [comment]
@charleneauger 
Thanks for the info. Works :)
Bug can therefore be closed
