### ISSUE TITLE
[BUG] Deployment tool doesnt work for http

### ISSUE THREAD

**Issue by gordnhoo** [OCSInventory-NG/OCSInventory-ocsreports#1610]
**OCS Inventory version**
Version : [2.12.1]

**Describe the bug**
The bug s when i try to deploy in http it always passes over to https

**To Reproduce**
Just change protocol to HTTP in the configuration from ocs inventory try to deploy it and windows agent sends this back even thought i chose http
ERROR *** DOWNLOAD => Failed to download Metadata file <https://192.168.100.41/download/1718620163/info> to <C:\ProgramData\OCS Inventory NG\Agent\download\1718620163\info>

**Expected behavior**
the agent log from windows should connect to http not https

**Screenshots**

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment]
Hi,

The setting might be a little confusing but OCS will always download the info file with HTTPS.
HTTP / HTTPS setting for deployment is meant for fragment download (the actual content of the deployment) while the meta data are always downloaded as HTTPS for security reason as it may contain sensitive data.

We highly recommend to setup HTTPS in order to deploy packages.

Regards,
Gilles.
