### ISSUE TITLE
French accent and speed are not displayed correctly

### ISSUE THREAD

**Issue by gitdevmod** [OCSInventory-NG/OCSInventory-ocsreports#166]
French accent and speed are not displayed correctly in ocsreports webpage. Speed should be 10Gb/s

![ocs](https://cloud.githubusercontent.com/assets/2040775/20796479/96212af2-b7d6-11e6-9c02-ea1e89c72665.PNG)

Agent: 2.1.1.1 OS: Windows 2012R2 (I'm using 2.1.1.1 because we still have XP and use same version everywhere)
OCSNG_UNIX_SERVER-2.2.1 with Debian 7.11
PHP Version : 5.4.45-0+deb7u5 (apache2handler)
Web Server : Apache/2.2.22 (Debian)
Database Server : (Debian) version 5.5.53-0+deb7u1
Database ocsweb:
mysql> show variables like "character_set_database";
+------------------------+-------+
| Variable_name                | Value  |
+------------------------+-------+
| character_set_database    | utf8   |
+------------------------+-------+
1 row in set (0.01 sec)

Thanks in advance

**Comment by gillesdubois** [comment]
Hi,

This problem is not present on windows agent 2.3.0.0 with ocsinventory server 2.3RC

![encodingright](https://cloud.githubusercontent.com/assets/9396603/21451400/35355508-c8ff-11e6-8bc4-212da16212b1.png)

I think you should try to upgrade your agent on a windows 7 computer to see if the agent upgrade solve the problem.

Regards,
Gilles Dubois.

**Comment by gitdevmod** [comment]
Hi Gilles,

Ok I'll give a try when 2.3 will be released. What about the speed ?
