### ISSUE TITLE
Update from 1.0.5 to 2.3RC

### ISSUE THREAD

**Issue by a11g0rhythm** [OCSInventory-NG/OCSInventory-ocsreports#187]
HI,
I upgrate instalation of OCS  from 1.0.5 to 2.3RC. Cannot login.
Ocs upgrade database after update ?

**Comment by gillesdubois** [comment]
Hi,

Upgrading from 1.0.x to 2.3RC is not a good idea since it's not supported and not tested by the team.
If you need to upgrade from 1.0.x. you should do it using intermediate versions ( 1.0 -> 1.3 -> 2.0 -> 2.3 for example )

I also recommand you to upgrade your ocs in the future because these kind of upgrade process can be a nit overhelming.

Regards,
gilles dubois
