### ISSUE TITLE
Menu improvements

### ISSUE THREAD

**Issue by pilch-cit** [OCSInventory-NG/OCSInventory-ocsreports#220]
### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
Hello,

the work-flow could be improved if the computer details menu (on the left side) is always visible.
I would suggest an menu that scrolls along or a menu that has its own frame an does not scroll at all.

Subcategories, providing a way to jump to a certain category with one click, would further improve the flow.

What are your thoughts on this?

Best Regards
Alexander Pilch

**Comment by gillesdubois** [comment]
Hi @pilch-cit ,

I think that a really good idea, on computer with a lot of information i can be annoying to have to scroll up in order to reach an other tab of the inventory.

I'm adding this as an improvement.
If you are lucky i could be implemented in the next minor version :)

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi @pilch-cit ,

This has been added to the interface and will be available in the next version
Thx for your contribution.

Regards,
GIlles Dubois.
