### ISSUE TITLE
Duplicate entries keep popping up

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [OCSInventory-NG/OCSInventory-ocsreports#223]
### General informations
Operating system : Ubuntu 14.04

### Server informations
Php version : 5.5.9
Mysql / Mariadb / Percona version : Mysql 5.7.17-11
Apache version : Apache/2.4.7

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
If i look under duplicates. Some of the same computers keep coming up. I have merged these before, but they keep coming back.

The server is on 2.3, and the agents are still on v2.1.1.

![image](https://cloud.githubusercontent.com/assets/7766580/23311774/93be7c32-fab7-11e6-856f-495c3f22102c.png)

Shouldn't ocs be able to manage the duplicates if they were merged at one stage?

**Comment by gillesdubois** [comment]
Hi, @phillip-white-sociomantic 

Indeed OCS Inventory manage duplicaties automaticaly but sometimes some duplicate can pass the server's test.

See the auto_duplicate level may be your problem come from there :
![capture du 2017-02-27 08-38-03](https://cloud.githubusercontent.com/assets/9396603/23352564/31db1120-fcc8-11e6-9b1d-e3a59ccf4987.png)

Regards,
Gilles Dubois.

**Comment by phillip-white-sociomantic** [comment]
@gillesdubois I have been testing over the past few weeks. Unfortunately OCS does not seem to be merging the duplicates.

It is set as default in the config:
![image](https://cloud.githubusercontent.com/assets/7766580/23697598/a4f1c952-03e8-11e7-81d1-059f925519d6.png)

I have tested some things:
1. Removing the asset from OCS and seeing what happens when the asset come back by itself. - It comes back with duplicates.
2. Removing the agent (v 2.1.1) from the client and re-installing. - Eventually it comes back as a duplicate.
3. Merging the assets. - Eventually it comes back as a duplicate.

As you can see, some assets come up as duplicates. The assets have the same hostname, mac and serial.

![image](https://cloud.githubusercontent.com/assets/7766580/23697705/16c4e438-03e9-11e7-88b1-21d8f34105cf.png)


Any ideas how to fix this?

**Comment by gillesdubois** [comment]
Hi @phillip-white-sociomantic ,

Look like a problem with the server : https://github.com/OCSInventory-NG/OCSInventory-Server/issues/50
The problem look like an update problem on Mysql 5.7.X server

I will try to solve this problem asap :)

Thanks for your reports.

Regards,
Gilles Dubois.

**Comment by DDettmering** [comment]
I'm also suffering from this bug ([see my OCS forum question about it](http://ask.ocsinventory-ng.org/6992/mass-duplicate-entries-of-citrix-terminal-servers?show=6992#q6992)).
[But I even can't clean up the duplicates](http://ask.ocsinventory-ng.org/6990/cant-clean-duplicate-entries) and till today nobody could give me any hint how to solve this!

In the moment our OCS inventory is useless.

Regards

Dirk Dettmering

**Comment by ankitwaghela09** [comment]
I have found issue, changes in CPU Current Speed creates duplicate entry.

**Comment by theogrs** [comment]
Hi @ankitwaghela09 

How have you fix it ?

Thanks

**Comment by JulienG78** [comment]
Hi,
We have updated our server in 2.3.1.1 also with all our 200 clients, we have a lot of duplicates.
We take several times per day to clean the hundreds of duplicate entries :(

I hope a fix will be found very sound :)

**Comment by gillesdubois** [comment]
Hi @JulienG78 

There is no 2.3.1.1 version for the server, you might be in 2.3.1. 2.3.1.1 is a windows agent version. Did you try with the latest agent version ? 

Regards,
Gilles Dubois.

**Comment by JulienG78** [comment]
Hi,
Yes clients has the 2.3.1.1 version installed.
And yes the server is in 2.3.1

I have disabled the TRACE_DELETED option as mentioned in another thread, but it doesn't fix my problem.

I have duplicate entries with different mac adresses, or also same mac adress, same serial number.

Like this : 

![28-11-2017 16-14-46](https://user-images.githubusercontent.com/24435635/33327240-4d055aca-d457-11e7-9d9d-0ccf51d34b3a.png)

**Comment by gillesdubois** [comment]
How did you set your auto duplicate level ?

**Comment by JulienG78** [comment]
First it was by default with hostname, mac adress and serial number.
Then I tried with only hostnames, but still the same :(

it was the same when we were in version 2.1

**Comment by JulienG78** [comment]
After 3 days I have now more than 430 duplicates entries ^^.
Here is my conf
![01-12-2017 15-59-53](https://user-images.githubusercontent.com/24435635/33488416-cc00f554-d6b0-11e7-84c6-3797b0292c23.png)
![01-12-2017 16-00-09](https://user-images.githubusercontent.com/24435635/33488417-cc1d972c-d6b0-11e7-92b1-889447d25bec.png)

**Comment by DDettmering** [comment]
As I wrote in the OCS forum (http://ask.ocsinventory-ng.org/6992/mass-duplicate-entries-of-citrix-terminal-servers?show=6992#q6992 & http://ask.ocsinventory-ng.org/6990/cant-clean-duplicate-entries): A complete reinstallation of OCS has solved my problem with the mass duplicates. I don't know what screwed my first installation up. But because my problem has vanished I have no intention to explore further the problem.

**Comment by JulienG78** [comment]
Duplicates still doesn't work.
Here is what I did since this last weekend :
- Erase the computer names table on the database.
- Complete reinstallation of ocsserver on debian with all default settings, nothing custom.

Duplicates are still showing up, even with same hostname, macadress, ipadress.

I'm going to test with a new database, hope it will work...

**Comment by JulienG78** [comment]
Still having the issue after a complete OCS reinstallation.
I have also droped the SQL database for a fresh new one, still not fixed.

Now I have a clean OCS install, a clean database, I'm sure the problem is about the 2.3.1 server release on Debian having a bug.
Before that we were in the 2.1 and it was working perfectly :S

**Comment by elcarles** [comment]
Hi, I have exactly the same problem with duplicates.

We had ocs-server v.23 and i had a problem with duplicates. I upgraded the version to 2.4 but the problem continues. A lot of duplicates everyday. 

OCSServer 2.4
Operating system : RHEL 6.9
Php version : 5.5.16
 Mysql 5.6.20-68.0 no localhost
Apache version : Apache/2.2.15


Agents are still on v2.3.0

¿Any idea? 


Thank you.

**Comment by mxroo** [comment]
We are having this issue as well. We upgraded to 2.3 and then 2.4 and still getting loads of duplicates per day, with no discernable reason why.
We also droped the SQL database for a fresh new one, still not fixed.

**Comment by allancarlosvr** [comment]
I had the same problems, but, after to upgrade my OCS for version 2.4. The problem is solved in part.

I still problem when I change the hostname, because make a new entry in my OCS, generating a duplicate value. 

I unchecked hostname in AUTO_DUPLICATE_LVL hostname. Checked only Serial and AssetTAG

Anyone can help me?

**Comment by 0kaym0** [comment]
Same here, upgraded from 2.4 to 2.4.1 but still have lots of duplicates a day. I don't know where to find or what kind of tests may be done.

windows agent 2.1.1.1, 2.3.0.0 and 2.3.1.1, move AUTO_DUPLICATE_LVL in différents configurations nevermind.

If someone have a kind of solution an idea ?

**Comment by latern02** [comment]
Hey, same here, after the upgrade from 2.4 to 2.4.1.

Any solution known?

**Comment by 0kaym0** [comment]
Still the same on 2.5 with windows agents 2.3.0.0, 2.3.1.1

Is there any way to find where is the problem ?

**Comment by mrdetra** [comment]
here also the problem occurs with OCS 2.5 , Agent 2.3.1.1 and glpiplugin 1.5.2 .

getting about 20 duplicates/day .

**Comment by 0kaym0** [comment]
Sounds good with OCS 2.5, agent 2.4.0.0.

Most duplicates stop popping up (still have 1 or 2 against 60 a day before)

**Comment by silvanet123** [comment]
I have OCS 2.6 with agent 2.4.0.0 and I am getting many duplicates.  We have 10,000 machines.  
I recently built a new OCS server running 2.6 and utilizing the 2.4.0.0 agent.  My old server was upgraded to 2.6 but we had the 2.3.x agents and there were very few duplicates there.  From my perspective, it seems to be the new agent.  Is there anything we can do to help diagnose the issue?

**Comment by vemi2709** [comment]
I had a similar issue in my test environment, turned out to be a missing extension table:
error.log:
DBD::mysql::db do failed: Table 'ocsweb.scheduledtasks' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Duplicate.pm line 262.
activity.log:
... ;OCS-NG_WINDOWS_AGENT_v2.3.1.1;duplicate;replacing_error
I had tested the Scheduled Tasks -extension and disabled it. Re-enabling it solved the case.
