### ISSUE TITLE
Exit button does not appear

### ISSUE THREAD

**Issue by mpiske** [OCSInventory-NG/OCSInventory-ocsreports#229]
The exit button does not appear when I set a password in apache

https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04

![exit](https://cloud.githubusercontent.com/assets/20438531/23587548/8b806f76-018d-11e7-89f4-429bc5d377be.png)

**Comment by gillesdubois** [comment]
Hi @mpiske ,

OCS' default behavior is to not show the logout button when an Apache auth is set because it often mean that a external auth methode is being used.

I don't know if that a good idea to show it, since ocsinventory doesn't manage the auth anymore.
Think about a kerberos login, the logout button won't work in this case... showing it can be frustrating for some user.

Regards,
Gilles Dubois.

**Comment by mpiske** [comment]
Ok, thanks
