### ISSUE TITLE
[2.2RC1] Enlarge Number Show Entries

### ISSUE THREAD

**Issue by prodced** [OCSInventory-NG/OCSInventory-ocsreports#25]
Hello

In 2.2RC1 release we are now limited to a maximum of 100 entries visualization.
Is it possible to enlarge the number or even to the ALL function to allow me to see all PCs.

**Comment by gillesdubois** [comment]
Hello,

You're right, you can't actualy display all the computers (Because of performance issue on big database)
I don't know why you need to display all computer but on the 2.2Rc1 you have a search bar (Top-Right of the table) which can help you to find what you need.

However, a lot of things has change on this 2.2 so If you explain me what you want to do exactly, i could help you on how to make it on OCS 2.2 (Maybe there is an other way) :)

Regards,
Gilles Dubois.

**Comment by prodced** [comment]
Bonjour

N'yant pas forcement une grosse base de PC (environ 300) cela nous permet en un coup d'oeil de voir tous les pc de notre parc 

Cela nous évite de faire des exports CSV.

Cordialement

**Comment by prodced** [comment]
De plus lorsque l'on supprime un objet, notre nombre de résultat revient au nombre de 10 par défaut

**Comment by gillesdubois** [comment]
Bonjour,

Après quelques tests un affichage a 250 / 500 entrées ne pose pas de soucis de performance (Même sur les grosses bases).
La limite va être augmenté dans un fix ultérieur.

Une notification sur cette issue sera disponible quand le fix sera publié.

Merci de votre contribution au projet OCS.
Cordialement, Gilles Dubois.

**Comment by pchamo** [comment]
Please, don't restrict the number of computers displayed. To diplay all the computers in the database is sometimes needes, not only to CSV exports, but to review that info. Thank you very much.
Sincerely, Pablo Chamorro

**Comment by gillesdubois** [comment]
So a lot of people was complaining about this entries number.
I updated the datatable plugin in order to display between 10 and All entries.

Thanks for contributing OCSInventory-ng :)

Have a nice day.
Regards, Gilles Dubois.

**Comment by nirgal** [comment]
Patching the 3rd party library only works temporarily. Please find another solution. This fix will be trashed on next library update!
