### ISSUE TITLE
Report / Columns

### ISSUE THREAD

**Issue by headquaker** [OCSInventory-NG/OCSInventory-ocsreports#27]
It seems that it is not possible to select the same columns in every reports.
In multi criteria search, it is possible to display hard disk space information, which it is not possible to do  in the main report "All computers"

Other example in all computers, it is possible to show the serial number, which is not possible to do that in multi criteria search.

To say it simple: it should be possible to show each field present in a computer information.

**Comment by gillesdubois** [comment]
Hello,

A fix will be available today.

Firstly, you right some of computers columns weren't in the multi search, i fixed that now more computer columns can be requested from the dropdown in the multi search.

In a second time, If you still don't see some of these columns that "normal". for the multi search ocs inventory do not retrieve all the computer informations because he just need some basics informations in order to perform action on it... not retrieving all computer informations also improve speed query and result creation.

Fields added to multi search : 
   - Processors thread
   - Processors numbers
   - Quality
   - OS : Owner
   - OS : Company
   - Network : Domain(s)
   - Network : Ip Address
