### ISSUE TITLE
Add SMART counter reading disk

### ISSUE THREAD

**Issue by mickythekiller** [OCSInventory-NG/OCSInventory-ocsreports#29]
a good feature for ocs is to add SMART counter reading disk

http://forums.ocsinventory-ng.org/viewtopic.php?id=337

https://blueprints.launchpad.net/ocsinventory-windows-agent/+spec/ocs-agent-hdd-smart-reading

**Comment by gillesdubois** [comment]
Hello,

Even if that a good idea ocs inventory is not a monitoring software but an inventory one.
However if you want you can still develop this feature as a plugin if you really need it.
For the 2.2 a documentation will be available soon on how to develop a plugin, you will be able to use it in order to create your proper plugin / custom inventory.

Regards, 
Gilles Dubois
