### ISSUE TITLE
import local error Bad Request

### ISSUE THREAD

**Issue by franck51000** [OCSInventory-NG/OCSInventory-ocsreports#306]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian

### Server informations
Php version : PHP 5.4.45
Mysql / Mariadb / Percona version :  MariaDB Server version 5.5.56-MariaDB 2.3.1
Apache version : Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.45 

### OCS Inventory informations
Ocsreports version : 2.3

### Problem's description
when importing an OCS file in local import this goes back an error

Erreur HTTP/1.1 400 Bad Request 

link printscreen

![errocs](https://user-images.githubusercontent.com/32701581/32106849-2bb10c04-bb2d-11e7-8ed1-2578e4e24c6d.jpg)

Best Regard

**Comment by gillesdubois** [comment]
Hi,

Can you give me the method you used to generate the .ocs file ?

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
ping @franck51000  ?

**Comment by afl-iris** [comment]
this error seems to come from HTTP header format in post_ocs_file_to_server (file: require/function_files.php)

Host header is sent with "\r" terminator which is rejected by apache 2.4 (due to CVE-2016-8743 patch which enforce stricter header parsing ?)

with "\r\n" terminator, the import is completed...
