### ISSUE TITLE
Include Office Licence to have stats

### ISSUE THREAD

**Issue by headquaker** [OCSInventory-NG/OCSInventory-ocsreports#42]
It could be useful to have the ability to get all licences grouped by type or keys

**Comment by gillesdubois** [comment]
Hi,

Office licence is not an ocs core functionality however a plugin which retrieve office licences and manage them already exist.
If you want to improve the already existing plugin (officepack) you should check and re-open an issue here : https://github.com/PluginsOCSInventory-NG/officepack

If you want to contribute to all ocs plugins in a global way you should follow this link : https://github.com/PluginsOCSInventory-NG

Thanks for contributing the ocs inventory project.
Regards, Gilles Dubois.

**Comment by headquaker** [comment]
I was a good idea to include that directly.

Plugins are always a source of problems because it is not "by default".

**Comment by gillesdubois** [comment]
Ocs 2.2 come with an integrated plugin engine which help you in the plugin installation process (everything is automated by the ocs core you have nothing to do on the server).
A documentation for the plugin engine will be available soon.

However i can understand that can be quite boring to install a plugin when you use it as much as the core functionalities but we can't include a plugin by default because that not an easy task.

On ocs, include a plugin basically mean : 
- Modify the server code
- Modify the webconsole code
- Modify the agent code
- Tests

The officepack plugin is one of the most downloaded plugin and is working very well. it will be a wast of time and ressources to start to include it in the ocs core.

Nonetheless if you need some help on how to install a plugin and how to make it work you can always contact us : 
github for plugin : https://github.com/PluginsOCSInventory-NG
ask : http://ask.ocsinventory-ng.org
mail : contact@ocsinventory-ng.com

Regards, Gilles Dubois.

**Comment by headquaker** [comment]
Could you explain how to install the plugins for office pls?

**Comment by headquaker** [comment]
Est ce que l'ancien vbs pour office est compatible avec le plugins 2.2 ?

**Comment by gillesdubois** [comment]
Pour officepack pour la 2.2 : 
https://github.com/PluginsOCSInventory-NG/officepack/releases/download/1.0/officepack.zip

Des instructions rapide sont disponible ici : https://github.com/PluginsOCSInventory-NG/officepack/releases/tag/1.0

Oui l'ancien vbs est toujours compatible pour la 2.2 :-)

**Comment by headquaker** [comment]
j'ai installé le plug mais je ne vois pas les infos.

Ou faut-il aller ensuite ?

**Comment by gillesdubois** [comment]
Un reload apache / deconnexion - reconnexion est peut être necessaire en fonction du système utilisé pour le serveur.

Ensuite c'est comme un plugin classique tu met le vbs sur tes agents et tu lance un inventaire.

Les infos seront remonté sur l'inventaire de la machine dans software ou alors dans le menu Plugins --> Office Key Managment

**Comment by headquaker** [comment]
Par contre il n'y a plus la répartition par type de licences et combien il y en a.

**Comment by gillesdubois** [comment]
Il faudrait peut-être créer une issue sur le plugin office pack en expliquant la régression, je ferais un fix dès que j'ai du temps libre.

**Comment by gillesdubois** [comment]
La suite des modifications / notifications se fera sur cette issue.
https://github.com/PluginsOCSInventory-NG/officepack/issues/1
