### ISSUE TITLE
OCS Unix Server 2.2 - IPDiscover

### ISSUE THREAD

**Issue by Krakozaber** [OCSInventory-NG/OCSInventory-ocsreports#44]
Can't delete a record from "Identified peripherals list"

**Comment by gillesdubois** [comment]
Hi,

Can you please give more informations about your issue ?
How to reproduce your problem can be a good start.

Regards, Gilles Dubois.

**Comment by Krakozaber** [comment]
Upgrade OCS Unix Server from 2.1.2 to 2.2

1. Open http://ocs/?function=show_ipdiscover
2. --Show all my subnet--
3.  Open http://ocs.axion.com/index.php?function=ipdiscover_info&prov=ident&head=1&value=<net_name>
4. Click on 'x' action
5. On allert click 'Ok"
6. Nothing happens, the value remains unchanged

**Comment by gillesdubois** [comment]
Ok, there is problem on this delete action i'm on it.
You will be notified when a fix will be commited.

Thanks for contributing to the ocs inventory project.
Regards, Gilles Dubois

**Comment by Krakozaber** [comment]
Thank you for your work :-)

**Comment by Krakozaber** [comment]
require/function_table_html.php  str. 1879 
`$row[$key]=$value_of_field." (<small>".$constr."</small>)";`

plugins/main_sections/ms_ipdiscover str. 34 to 40
```
if(isset($protectedPost['SUP_PROF'])){
$sql="DELETE FROM netmap WHERE mac='%s'";
mysql2_query_secure($sql, $_SESSION['OCS']["writeServer"],$protectedPost['SUP_PROF']);
$sql="DELETE FROM network_devices WHERE macaddr='%s'";
mysql2_query_secure($sql, $_SESSION['OCS']["writeServer"],$protectedPost['SUP_PROF']);
unset($_SESSION['OCS']['DATA_CACHE']['IPDISCOVER_'.$protectedGet['prov']]);
}
```

**Comment by ironiq** [comment]
The problem is the line 1879 in require/function_table_html.php. For a workaround, change it to this:

$row[$key]=$value_of_field;

In this case you won't see the manufacturer, but you'll be able to delete.

**Comment by gillesdubois** [comment]
Hi,

Sorry for the delay.
The problem you encountered is not a bug.

With ocs inventory you can delete registered subnet, not the unknow one.
For example if you have a network in 192.168.0.0 you can create an alias for it like "My Sub Net Number 1".
If you click on the grey cross this will only delete the alias for this network and not the ipdiscover data.
This has been done like that because if you delete entirely a network you can delete some network informations from the inventoried computers.

However from your feedback, this thing look confusing, a fix will be commited in order to make this page easier to use and understand

Thanks for contributing the ocs project.
Regards, Gilles Dubois.

**Comment by Krakozaber** [comment]
No, you misunderstood me, the problem is not with the subnet, and with a bunch of IP+Mac is not observed in OCS, but defined in IPDiscover. Problem in passing parameters in MySQL.
Send:
require/function_table_html.php str. 1879
$row[$key]=$value_of_field." (<small>".$constr."</small>)";
but ib MySQL only $value_of_field.

**Comment by gillesdubois** [comment]
Ok, sorry we didn't speak about the same thing :-)

Your problem as been fix, some cosmetic changes has been done too and from your feedback an other bug has been found and solved as well.

Thanks you for contributing to the ocs project.
Regards, Gilles Dubois.
