### ISSUE TITLE
All computers page show incorrect RAM capacity #2

### ISSUE THREAD

**Issue by Mant1kor** [OCSInventory-NG/OCSInventory-ocsreports#475]
### General informations
Operating system : CentOS Linux 7 (Core)

### Server installation method
- [x] Install SH

### Server informations
Php version : 7.1.17
Mysql version : 5.7.22
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.4.1 (latest changes from github)

### Problem's description
Fix #469 didn't resolve the issue.

![default](https://user-images.githubusercontent.com/5281753/41416421-7e6542e6-6ff3-11e8-900e-7d8f88783a9f.png)

**Comment by herminio-junior** [comment]
in the file "ms_all_computers.php": / usr / share / ocsinventory-reports / ocsreports / plugins / main_sections / ms_all_computers $

I changed line 129 to $ l-> g (568) => "memory as cover",

instead of: $ l-> g (568) => "SUM (m.capacity) as cover",

Although some computers do not report the total capacity, I get very close to the correct result.

**Comment by Mant1kor** [comment]
> I changed line 129 to $ l-> g (568) => "memory as capa",
Doesn't work to me (No data available in table).

**Comment by gillesdubois** [comment]
Hi,

This fix has been reverted to the original code.

Thus, the original problems is still there (Difference between memory table and hardware value). 

The value inventoried in hardware and in memory table are stored in differents place in OS.

The hardware table have the "Usable ram properties". The memory table have the RAM full and detailed inventory. That why values may differ.

Regards,
Gilles Dubois.
