### ISSUE TITLE
How do I participate in translator Chinese?

### ISSUE THREAD

**Issue by jackadam1981** [OCSInventory-NG/OCSInventory-ocsreports#648]
I want help to translator Chinese zh-cn.

**Comment by gillesdubois** [comment]
Hi @jackadam1981, 

To translate OCS Inventory in Chinese language, you have to take the default English file, (https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/master/plugins/language/en_GB/en_GB.txt) translate every line in Chinese and send it us. (you can do it through this issue) 

In the case you need help on the usage context of the translation we remain at your disposal. 

Since OCS Inventory is not translated in Chinese at the moment, we will have to make some modifications to include this new language. Once the integration is complete, you will see the new language in the next OCS Inventory version or in the next nightly build :) 

After that, you will be able to submit minor modifications by creating a pull request. (See https://help.github.com/articles/about-pull-requests/ and https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/567 as an example)

Regards,
Gilles Dubois.

**Comment by pchamo** [comment]
Hi, I attach my es_ES.txt for your consideration.

[es_ES_pch.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/2714990/es_ES_pch.txt)
[es_ES.txt](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/2714981/es_ES.txt)

Please, run a vimdiff to see the changes. Here some screenshoots of how it looks the fields computers menu:

http://prntscr.com/m0mmv1
http://prntscr.com/m0mnzc

Thank you.
