### ISSUE TITLE
Publishers are not consistent

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#701]
### General informations
Operating system : Ubuntu 18.04

### Server installation method ( Only one choice )
- [X] DEB Package
- [ ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### Server informations
Php version : 
Mysql / Mariadb / Percona version : 
Apache version : 

### OCS Inventory informations
Ocsreports version :  2.6-RC

### Problem's description
The "Publisher" info returned by agents is not consistent.

Let's look at this extract from my "all softwares" view:

![image](https://user-images.githubusercontent.com/8179031/53974714-75e28e80-4103-11e9-9b9f-53d0adb3d413.png)

It is clear for a human that most of the softwares in this extract are published by "Apple". However, OCS inventory shows "3.0.6, Copyright 2002-2014 Apple...", "3.13, Copyright 2003-2015 Apple..."

### Proposal: 

That would be great if OCS would be able to recognise that all these software have in fact "Apple" as publisher.

I have written a function that does something like that in my PR related to CVE-SEARCH integration: https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/594/files#diff-700bf89bce96c8ba0c587d8827b7f1e4R544

**Comment by StCyr** [comment]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/702

**Comment by gillesdubois** [comment]
Hi @StCyr,

I understand your problem but i think it's more the publisher's problem than our.

We can't rework every publishers information because our goal is to provide the data, not to modify it. 

Also, if we start to rework publishers data, we will become responsible of what's displayed in OCSInventory. With the number of variations in publishers name depending on a lot of criteria (special char / OS related data truncate / OS version / installation source / alphabet) it will become unbearable and also a big source for bugs.

Just as an example, the same software on a Russian Windows can be totally different in an European version. Also, this behavior to rework data can lead to false positive if the system is not well-build enough.

Regards,
Gilles Dubois.
