### ISSUE TITLE
Not displayin data in hardware, network, devices

### ISSUE THREAD

**Issue by slawekdw** [OCSInventory-NG/OCSInventory-ocsreports#757]
Helo
I use the slackware system 14.2 ocsinventory works great, but unfortunately it does not show me information in the network, hardware and device tables. jellie gives you a search according to the criteria that I find the device. I do not have any errors in the logs.
comparing the demo version of ocsreports I noticed that I have no ID_REQ and sql query affich_networks in the SQLNOLIMIT table

 PHP 5.6.40
Apache 2.4.39
 OCS 2.6
see the debug tab in the network tab
[OCS Inventory.pdf](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/files/3257384/OCS.Inventory.pdf)
regards
Slawek

**Comment by PCManiacpt** [comment]
Greetings,

I am a slackware user myself and recently installed OCS on a slackware server for my work network.
You refered that you are using the latest and most stable slackware version (14.2).

From tests I have made in, say, centOS (to compare how it works there vs slackware), is that it needs php 7 for instance and from what you noted, you are using the one that ships with 14.2.

Would start by upgrading that, perhaps apache as well and start from there.

**Comment by gillesdubois** [comment]
Hi,

This problem is not present on our test environnements (Redhat / CentOS / Debian / Ubuntu).
Unfortunatly, we don't support slackware and won't install a development / test server since its usage is marginal.

If you want support from the open source community i recommand you to install your server on a supported distribution.

In the case you can't install another dsitribution and need specific support, you can get professional support for our partners using the following contact form : https://ocsinventory-ng.org/?page_id=126&lang=en

Regards,
Gilles Dubois.
