### ISSUE TITLE
[HELP] data renderer

### ISSUE THREAD

**Issue by slawekdw** [OCSInventory-NG/OCSInventory-ocsreports#761]
After update Ocsreports and inventory to version 2.6 not displaying hardware data
ocsreports/index.php?function=computer&head=1&systemid=530&cat=network
displaying only headers from network table. If i replace index.php? to ajax.php? then browser displaying
### {"draw":null,"recordsTotal":3,"recordsFiltered":3,"data":[{"DESCRIPTION":"Realtek PCIe GBE Family Controller","TYPE":"Ethernet","SPEED":"1 Gb\/s","MTU":"","MACADDR":"00:19:99:C1:7B:91","STATUS":"Up","IPADDRESS":"10.101.102.59","IPMASK":"255.255.255.0","IPGATEWAY":"10.101.102.1","IPSUBNET":"10.101.102.0","IPDHCP":"10.101.102.1","ACTIONS":" "},{"DESCRIPTION":"Karta Microsoft ISATAP","TYPE":"Other (see MIB)","SPEED":"100 Kb\/s","MTU":"","MACADDR":"00:00:00:00:00:00","STATUS":"Down","IPADDRESS":"","IPMASK":"","IPGATEWAY":"","IPSUBNET":"","IPDHCP":"","ACTIONS":" "},{"DESCRIPTION":"Teredo Tunneling Pseudo-Interface","TYPE":"Other (see MIB)","SPEED":"100 Kb\/s","MTU":"","MACADDR":"00:00:00:00:00:00","STATUS":"Down","IPADDRESS":"","IPMASK":"","IPGATEWAY":"","IPSUBNET":"","IPDHCP":"","ACTIONS":" "}],"customized":true}

as you can see the data is but unfortunately they are not displayed in the table

PHP 5.6.40
Ocs 2.6
Apache 2.4

**Comment by gillesdubois** [comment]
Hi,

This problem is not present on our test environnements (Redhat / CentOS / Debian / Ubuntu).
Unfortunatly, we don't support slackware and won't install a development / test server since its usage is marginal.

If you want support from the open source community i recommand you to install your server on a supported distribution.

In the case you can't install another dsitribution and need specific support, you can get professional support for our partners using the following contact form : https://ocsinventory-ng.org/?page_id=126&lang=en

Regards,
Gilles Dubois.
