### ISSUE TITLE
[BUG] str_replace &amp; to &

### ISSUE THREAD

**Issue by slawekdw** [OCSInventory-NG/OCSInventory-ocsreports#767]
**OCS Inventory version**
Version : 2.6

**Describe the bug**
No data in hardware, network, software, devices.
Solution:
in file oscreports/require/function_table_html.php replace line 201
from: $address = "ajax.php?" . http_build_query($addressoption);
to $address = "ajax.php?" . str_replace('&amp_ular;' , '&', http_build_query($addressoption));

&amp_ular; without _ular

see screenshot from firefox developer console
without str_replace:
![ocs_bez](https://user-images.githubusercontent.com/46574829/59344665-dc80d500-8d0e-11e9-8ee4-f5d8554fecaa.jpg)

with str_replace:
![ocs_z](https://user-images.githubusercontent.com/46574829/59344702-e571a680-8d0e-11e9-85e3-07e0bf220200.jpg)

Please cofirm this bug.
PHP 5.6.40
OCS 2.6
System: Slackware 14.2

**Comment by florian-lutz** [comment]
Hi there, I had the same problem/bug regarding wrongly encoded &amp; in AJAX-URLs.

I can confirm it, but from the server configuration side. The solution was to add 

`php_value arg_separator.output "&"`

to /etc/apache2/conf-enabled/ocsinventory-reports.conf, because I normally have

`arg_separator.output = "&amp;"`

in my system-wide php.ini, which is considered by http_build_query().

**Comment by Parnoud** [comment]
i think this bug is link to my  #811 .  The Post data are send to db and you get those "&gt;" stock in db.

**Comment by Lea9250** [comment]
Hi @slawekdw,
It seems like this issue has been resolved, I am not able to reproduce this with the 2.9 version.

Regards,
Léa
