### ISSUE TITLE
show main user of any pc

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/OCSInventory-ocsreports#792]
**Is your feature request related to a problem? Please describe.**
i often don't know which person i musst call if a problem exist on a pc - last logged on user did not help often

**Describe the solution you'd like**
it would be nice if ocs-inventory can record the last 5 users - it would be fantastic if there can made a statistic who is logged the most time - ocs-inventory should only report the user if a user is logged in (not the last one - because this distorts the statistic.
we should be able to switch the staistic feature on and off for data security and company compliance.
So we know - this PC is a PC for a single user - and another one is a multisuer PC - and which one is the main user.
at the end we have an automatic list of the owner if any pc.
**Describe alternatives you've considered**
I thought of some mysql querys which does the user statistics  for me and stores the result in an extra table - but i have limited knowledge about this.

**Additional context**

**Comment by gillesdubois** [comment]
Hi @sokatra ,

I think it would be easier to interconnect with an Active Directory or something equivalent.

Let say i have a PC on OCS Inventory. This PC is in the domain and is linked to the main user. It would be easier to get the informations from the AD than OCS because OCS won't keep any data history.

Your second solution would be to interconnect with a CMDB which will make all the historisation and procession on your data.

Regards,
Gilles Dubois.

**Comment by sokatra** [comment]
the problem ist that AD doesn't has an advantage in comparison to admin info in ocs-inventory - the users often share their notebooks with other persons without informing the IT. Users come and go. 
 So the logonname is the only source where i can get the main user.
But thanks - i allready have glpi in use to geht the history of all users.
Kind regards

Sokatra
