### ISSUE TITLE
[BUG] Error In PLugin

### ISSUE THREAD

**Issue by meetgyn** [OCSInventory-NG/OCSInventory-ocsreports#851]
**OCS Inventory version**
Version :  OCSNG_UNIX_SERVER_2.6.tar.gz

**Describe the bug**
When I install a plugin I am getting the following error message:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''','','')' at line 1

**Screenshots**
![plugin](https://user-images.githubusercontent.com/3695608/68225873-da762600-ffcf-11e9-8887-ba71232c802a.PNG)

**Additional context**
Not all the plugins I put in the / usr / share / osc-repository / ocsreports / download folder

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by charleneauger** [comment]
Hi @meetgyn ,

You can install the nightly ocs inventory server version and retry to install the plugin. Many bugs has been fixed since the 2.6 release.
Link to download 2.6 nightly : http://download.ocsinventory-ng.org/nightly/

We keep this issue open until your feedback.

Best regards,
Charlene Auger
