### ISSUE TITLE
[BUG] cron_clean_cve.php

### ISSUE THREAD

**Issue by bajlek** [OCSInventory-NG/OCSInventory-ocsreports#954]
**OCS Inventory version**
Version : 2.7 Nightly build 19.5.2020

**Describe the bug**
Error after clearing CVE with cron_clean_cve.php

**To Reproduce**
1. run php /usr/share/ocsinventory-reports/ocsreports/crontab/cron_clean.cve.php
2. See error  Uncaught ArgumentCountError: Too few arguments to function Cve::clean_cve()

**Expected behavior**
It should remove all CVE in DB because I see only few CVE reports so I want to start again with cron_cve.php and fill up OCS DB with CVE from scratch

**Log file (optional)**
```
root@ocsng:/usr/share/ocsinventory-reports/ocsreports/crontab# php cron_clean_cve.php
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Cve::clean_cve(), 0 passed in /usr/share/ocsinventory-reports/ocsreports/crontab/cron_clean_cve.php on line 29 and exactly 1 expected in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php:341
Stack trace:
#0 /usr/share/ocsinventory-reports/ocsreports/crontab/cron_clean_cve.php(29): Cve->clean_cve()
#1 {main}
  thrown in /usr/share/ocsinventory-reports/ocsreports/require/cve/Cve.php on line 341
```

**Comment by charleneauger** [comment]
Hi @bajlek ,

With the last CVE feature, cron_clean_cve.php has been removed.

 Now CVE cleaning is done automatically when you run cron_cve.php thus, you won't need to clean them by yourself.
The cleaning function allowing to clean old CVE has been removed from CVE-search database.

If you want to remove all CVE from your OCS database you must do it yourself but we don't recommend it.

Best regards,
Charlene Auger

**Comment by bajlek** [comment]
So tell me how it is possible that I see only VLC CVE's but nothing about Microsoft, Adobe, LibreOffice, Office etc. ?? I see only 7 CVE records - that is not possible because we have 130 computers and 20 notebooks so there is clearly something wrong :-D

**Comment by gillesdubois** [comment]
Hi @bajlek ,

There is nothing about these softwares because the publisher's name retrived / set on WMI / Registry doesn't match with the publisher name when it comes to CVE References. In that case we introduced a matching system to rewrite in a dynamic way the publisher AND software name to have proper CVE Inventory.

Use CVE Engine : http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-management/

Use matching criterias : http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-match-regex/

Check CVE History : http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-visualize-history/

Note : you might need to update to the latest nightly.

In the case you need more help to setup these lists we do provide a professionnal service.

Regards,
Gilles Dubois.
