### ISSUE TITLE
[HELP] Changing DB Password - no "/etc/httpd/conf.d/z-ocsinventory-server.conf" file anywhere

### ISSUE THREAD

**Issue by mriske** [OCSInventory-NG/OCSInventory-ocsreports#998]
**Describe the bug**
Hey,
If i change the database password AND the entry in the file "/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php", i get the error "MySql connection problem 1045". 
I already read some tutorials, how to change the default DB Password, and all mention to also edit the "/etc/httpd/conf.d/z-ocsinventory-server.conf" file. I don't have this file anywhere on the server. I also SHOULD have an "/etc/apache2/conf-available/" but i already don't have the "/etc/apache2/" directory.

Anyone any idea why i dont have this file or folder? Can i create this file? What should be the content, other than the entry for the new password?

Server-Informations:
Version: 5.2.16-200.fc30.x86_64
Distribution: Fedora 30 (Workstation Edition)
PHP-Version: 7.3.20
Webserver: Apache/2.4.41 (Fedora) mod_perl/2.0.10 Perl/v5.28.2
Datenbank-Server: MariaDB Server version 10.3.17-MariaDB
Version OCSReports: 2.6

Thanks in advance!

**Comment by charleneauger** [comment]
Hi @mriske ,

I think your Apache installation isn't correct. I recommend you to reinstall apache2. In this way he should create the folder with all the default files. And next, reinstall OCS Inventory Server.

Best regards,
Charlene Auger

**Comment by mriske** [comment]
Thanks for the fast reply, but everything else is working fine?
I'll try to reinstall apache2 and OCS Inventory Server.

**Comment by charleneauger** [comment]
Hi @mriske ,

Is everything good ?

Regards,
Charlene Auger

**Comment by mriske** [comment]
Thanks for asking,

I'm relatively new to linux, so i hope i did it right, but seemingly not. :D

Yesterday i tried to uninstall apache2/httpd an he wanted to uninstall many, many dependencies. So i uninstalled httpd and ocsreports without dependencies.
Rebooted the system, installed httpd and ocsreports. And nothing was really working. I could access the logon page, but nothing more.

I also couldn't find the "/etc/httpd/conf.d/z-ocsinventory-server.conf" file. 

Something went really wrong, so i rolled back to an working snapshot, and nothing was lost.

Do you have a guide for this kind of reinstall?

If everything else fails, i reinstall the whole system and import the database. Would you recommend to run the docker variant? Would ocs work under windows (Docker Desktop)?

**Comment by gillesdubois** [comment]
Hi @mriske ,

From your anwser it seem you lack some basic knowledge on Linux. I would recommend you to get used to Linux environment before installing a software such as OCS.
If you are aiming for a production environement, we also provide professional support if you don't want / have time to get invested in knowing Linux environement.
Using Docker could be a solution but keep in mind that its still a linux system behind, it will also need you to have docker knowledge in order to maintain it and keep it up to date.

That said, as a good starting point what's your installation method ? Did you use our repository or did you install our software manually ?
Did you follow our wiki ? http://wiki.ocsinventory-ng.org/

Regards,
Gilles Dubois.
